import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'th' | 'vi' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    title: '颜值立方',
    subtitle: '语料管理平台',
    findCorpora: '发现您的语料',
    selectSource: '选择来源语言',
    selectTarget: '选择目标语言',
    pickSourceFirst: '请先选择源语言',
    contribute: '贡献',
    publications: '出版物',
    corpora: '语料库',
    synthetic: '合成数据',
    dashboard: '仪表盘',
    overviewTitle: '语料库概览',
    totalPairs: '总句对',
    languagesAvailable: '可用语言',
    tableNote: '此表显示了 10+ 个语料库，占整个集合的 62.50%。',
    contributors: '合作机构',
    corpus: '语料库',
    sentences: '句子数',
    percent: '占比',
    opusCollection: '颜值立方 集合',
    searchPlaceholder: '搜索...',
    sourceOpenSubtitles: 'OpenSubtitles',
    sourceUN: '联合国',
    langChinese: '中文',
    langEnglish: '英语',
    langThai: '泰语',
    langVietnamese: '越南语',
    langMalay: '马来西亚语',
    // Search Results
    resourcesFound: '找到资源',
    headerCorpus: '语料库',
    headerSentences: '句子数',
    headerTokens: '词数',
    headerSample: '预览',
    headerBilingual: '双语下载',
    headerMonolingual: '单语下载',
    formatMoses: 'moses',
    formatTmx: 'tmx',
    formatTxt: 'txt',
    // Domains
    selectDomain: '选择应用领域',
    domainAll: '全部领域',
    domainEcommerce: '跨境电商',
    domainTourism: '旅游文化',
    domainBusiness: '商务贸易',
    domainEconomy: '低空经济',
    domainGeneral: '通用领域',
    // Dashboard Specific
    dashTitle: '数据资产仪表盘',
    dashSubtitle: '颜值立方语料管理系统',
    dashLastUpdated: '最后更新',
    dashExport: '导出报告',
    dashViewOverview: '概览',
    dashViewBusiness: '业务洞察',
    dashViewLanguage: '语言特征',
    dashViewQuality: '质量控制',
    // Filters
    filterSource: '数据来源',
    filterSourceAll: '全部',
    filterSourceOfficial: '官方精校',
    filterSourceCommunity: '社区贡献',
    filterSourceSynthetic: '合成数据',
    filterDomain: '业务领域',
    filterMetric: '核心指标',
    filterMetricQuality: '质量分',
    filterMetricVolume: '数据量',
    filterMetricAlign: '对齐度',
    filterMetricRojak: 'Rojak浓度',
    filterScenario: '业务场景',
    filterCategory: '分类',
    // Categories
    catTerminology: '术语库',
    catQA: '问答对',
    catAlignment: '句对对齐',
    catProcess: '业务流程',
    catCase: '典型案例',
    catInstruction: '场景指令',
    labelSourceLang: '源语言',
    labelTargetLang: '目标语言',
    labelKeyword: '关键词查询',
    btnSwap: '交换',
    // KPI & Charts
    kpiRefinedPairs: '精校句对总数',
    kpiAvgDim: '平均标注维度',
    kpiRojak: 'Rojak 语言覆盖率',
    chartSentiment: '情感极性分布',
    chartTimeline: '语料积累时间轴',
    chartTimelineSub: '每日入库量 vs 总量 (含大促节点)',
    chartIntentTop: '意图排行',
    chartHeatmap: '意图热力图',
    chartPlatformSent: '渠道情感评分',
    labelPositive: '积极',
    labelNeutral: '中性',
    labelNegative: '消极',
    labelAngry: '愤怒',
    // Updated Generic Scenarios
    tabPresales: '咨询与问询',
    tabInsales: '交易与预订',
    tabAftersales: '客户服务',
    tabLogistics: '运营交付',
    tabReviews: '反馈评价',

    txtAnomalyAlert: '异常检测预警',
    txtAnomalyDesc: '过去4小时内 [渠道C/运营] 数据集检测到“愤怒”情绪激增。',
    txtInvestigate: '调查批次',
    txtNormalization: '归一化词典',
    txtLoanwords: '高频借词 (Rojak)',
    txtStyleDist: '风格分布',
    // Sample Preview
    samplePreview: '样本预览',
    lblSourceText: '源文本',
    lblRawInput: '原始输入 (口语)',
    lblNormalized: '标准化 (清洗)',
    lblLinguistic: '语言学洞察',
    lblNormMap: '归一化映射',
    lblLoanwords: '英语借词',
    lblStyle: '风格',
    lblRojak: 'Rojak 混合语',
    lblPragmatic: '语用层',
    lblUserIntent: '用户意图',
    lblSentiment: '情感倾向',
    lblVisual: '可视化',
    lblJsonl: 'JSONL',
    lblNoneDetected: '未检测到',
    lblNoNormNeeded: '此句无需归一化处理。',
    lblDisplaying: '显示 {current} / {total} 条句对',
    lblDetected: '已检测',
    lblNone: '无',
    // Tab Navigation
    tabDetail: '样本详情',
    tabKwic: '语境共现（KWIC）',
    tabStatistics: '词频统计',
    // Pagination
    paginationPrevious: '上一页',
    paginationNext: '下一页',
    // KWIC Analysis
    kwicTitle: '关键词语境分析',
    kwicKeywordPlaceholder: '输入关键词...',
    kwicContextWindow: '语境窗口',
    kwicContext3: '±3 词',
    kwicContext5: '±5 词',
    kwicContext7: '±7 词',
    kwicSearch: '搜索',
    kwicExport: '导出 CSV',
    kwicLeftContext: '左语境',
    kwicKeyword: '关键词',
    kwicRightContext: '右语境',
    kwicNoResults: '未找到结果',
    kwicResultCount: '找到 {count} 个结果',
    // Word Frequency Statistics
    freqTitle: '词频统计',
    freqSubtitle: '语料库词汇使用频率分析',
    freqTotalWords: '总词数',
    freqUniqueWords: '不重复词数',
    freqMostCommon: '高频词汇',
    freqFilterAll: '全部',
    freqFilterNoun: '名词',
    freqFilterVerb: '动词',
    freqFilterAdj: '形容词',
    freqFilterStopWords: '停用词',
    freqSortByFreq: '按频率',
    freqSortByAlpha: '按字母',
    freqWordColumn: '词汇',
    freqCountColumn: '频次',
    freqPercentColumn: '占比',
    freqTrendColumn: '趋势',
    freqLoading: '正在分析词频...',
    freqNoData: '暂无词频数据',
    freqSearchPlaceholder: '搜索词汇...',
    freqFilterByPos: '词性筛选',
    freqPosDistribution: '词性分布',
    freqWordCloud: '词云图',
    freqClickToSearch: '点击查看语境',
    freqToggleStopWords: '过滤停用词',
    freqNouns: '名词',
    freqVerbs: '动词',
    freqAdjectives: '形容词',
    freqOthers: '其他',
  },
  en: {
    title: 'Yanzhi Cube',
    subtitle: 'Corpus Management',
    findCorpora: 'Find your corpora',
    selectSource: 'Select source language',
    selectTarget: 'Select target language',
    pickSourceFirst: 'Select source first',
    contribute: 'Contribute',
    publications: 'Publications',
    corpora: 'Corpora',
    synthetic: 'Synthetic',
    dashboard: 'Dashboard',
    overviewTitle: 'Collection Overview',
    totalPairs: 'Total Sentence Pairs',
    languagesAvailable: 'Languages Available',
    tableNote: 'This table displays 10+ corpora, which make up a total 62.50% of the entire collection.',
    contributors: 'Our Contributors',
    corpus: 'Corpus',
    sentences: 'Sentences',
    percent: '% of Total',
    opusCollection: 'Yanzhi Cube Collection',
    searchPlaceholder: 'Search...',
    sourceOpenSubtitles: 'OpenSubtitles',
    sourceUN: 'United Nations',
    langChinese: 'Chinese',
    langEnglish: 'English',
    langThai: 'Thai',
    langVietnamese: 'Vietnamese',
    langMalay: 'Malay',
    // Search Results
    resourcesFound: 'Resources found',
    headerCorpus: 'CORPUS',
    headerSentences: 'SENTENCES',
    headerTokens: 'TOKENS',
    headerSample: 'SAMPLE',
    headerBilingual: 'BILINGUAL',
    headerMonolingual: 'MONOLINGUAL',
    formatMoses: 'moses',
    formatTmx: 'tmx',
    formatTxt: 'txt',
    // Domains
    selectDomain: 'Select Domain',
    domainAll: 'All Domains',
    domainEcommerce: 'E-commerce',
    domainTourism: 'Tourism & Culture',
    domainBusiness: 'Business & Trade',
    domainEconomy: 'Low-altitude Economy',
    domainGeneral: 'General',
    // Dashboard Specific
    dashTitle: 'Data Assets Dashboard',
    dashSubtitle: 'Yanzhi Cube Corpus Management System',
    dashLastUpdated: 'Last Updated',
    dashExport: 'Export Report',
    dashViewOverview: 'Overview',
    dashViewBusiness: 'Business Insights',
    dashViewLanguage: 'Language Features',
    dashViewQuality: 'Quality Control',
    // Filters
    filterSource: 'Corpus Source',
    filterSourceAll: 'All',
    filterSourceOfficial: 'Official',
    filterSourceCommunity: 'Community',
    filterSourceSynthetic: 'Synthetic',
    filterDomain: 'Domain',
    filterMetric: 'Metric',
    filterMetricQuality: 'Quality Score',
    filterMetricVolume: 'Volume',
    filterMetricAlign: 'Alignment',
    filterMetricRojak: 'Rojak Density',
    filterScenario: 'Scenario',
    filterCategory: 'Classification',
    // Categories
    catTerminology: 'Terminology',
    catQA: 'QA Pairs',
    catAlignment: 'Alignment',
    catProcess: 'Business Process',
    catCase: 'Typical Cases',
    catInstruction: 'Instructions',
    labelSourceLang: 'Source Language',
    labelTargetLang: 'Target Language',
    labelKeyword: 'Keyword Search',
    btnSwap: 'Swap',
    // KPI & Charts
    kpiRefinedPairs: 'Refined Sentence Pairs',
    kpiAvgDim: 'Avg. Annotation Dimensions',
    kpiRojak: 'Rojak Language Coverage',
    chartSentiment: 'Sentiment Dist.',
    chartTimeline: 'Corpus Accumulation Timeline',
    chartTimelineSub: 'Tracking daily intake vs. total volume with key events.',
    chartIntentTop: 'Top Intents',
    chartHeatmap: 'Intent Heatmap',
    chartPlatformSent: 'Channel Sentiment Score',
    labelPositive: 'Positive',
    labelNeutral: 'Neutral',
    labelNegative: 'Negative',
    labelAngry: 'Angry',
    // Updated Generic Scenarios
    tabPresales: 'Consultation',
    tabInsales: 'Transaction',
    tabAftersales: 'Support',
    tabLogistics: 'Operations',
    tabReviews: 'Feedback',

    txtAnomalyAlert: 'Anomaly Detection Alert',
    txtAnomalyDesc: 'Sudden spike in "Angry" sentiment detected in Channel C / Operations dataset over the last 4 hours.',
    txtInvestigate: 'Investigate Batch',
    txtNormalization: 'Normalization Dictionary',
    txtLoanwords: 'High Frequency Loanwords (Rojak)',
    txtStyleDist: 'Style Distribution',
    // Sample Preview
    samplePreview: 'Sample Preview',
    lblSourceText: 'Source Text',
    lblRawInput: 'Raw Input (Colloquial)',
    lblNormalized: 'Normalized (Clean)',
    lblLinguistic: 'Linguistic Insights',
    lblNormMap: 'Normalization Map',
    lblLoanwords: 'English Loanwords',
    lblStyle: 'Style',
    lblRojak: 'Rojak',
    lblPragmatic: 'Pragmatic Layer',
    lblUserIntent: 'User Intent',
    lblSentiment: 'Sentiment',
    lblVisual: 'Visual',
    lblJsonl: 'JSONL',
    lblNoneDetected: 'None detected',
    lblNoNormNeeded: 'No normalization needed for this sentence.',
    lblDisplaying: 'Displaying {current} of {total} pairs',
    lblDetected: 'DETECTED',
    lblNone: 'NONE',
    // Tab Navigation
    tabDetail: 'Sample Detail',
    tabKwic: 'KWIC Analysis',
    tabStatistics: 'Corpus Statistics',
    // Pagination
    paginationPrevious: 'Previous',
    paginationNext: 'Next',
    // KWIC Analysis
    kwicTitle: 'Key Word In Context',
    kwicKeywordPlaceholder: 'Enter keyword...',
    kwicContextWindow: 'Context Window',
    kwicContext3: '±3 words',
    kwicContext5: '±5 words',
    kwicContext7: '±7 words',
    kwicSearch: 'Search',
    kwicExport: 'Export CSV',
    kwicLeftContext: 'Left Context',
    kwicKeyword: 'Keyword',
    kwicRightContext: 'Right Context',
    kwicNoResults: 'No results found',
    kwicResultCount: 'Found {count} results',
    // Word Frequency Statistics
    freqTitle: 'Word Frequency',
    freqSubtitle: 'Corpus vocabulary usage analysis',
    freqTotalWords: 'Total Words',
    freqUniqueWords: 'Unique Words',
    freqMostCommon: 'Most Common',
    freqFilterAll: 'All',
    freqFilterNoun: 'Nouns',
    freqFilterVerb: 'Verbs',
    freqFilterAdj: 'Adjectives',
    freqFilterStopWords: 'Stop Words',
    freqSortByFreq: 'By Frequency',
    freqSortByAlpha: 'Alphabetical',
    freqWordColumn: 'Word',
    freqCountColumn: 'Count',
    freqPercentColumn: 'Percent',
    freqTrendColumn: 'Trend',
    freqLoading: 'Analyzing word frequency...',
    freqNoData: 'No frequency data available',
    freqSearchPlaceholder: 'Search words...',
    freqFilterByPos: 'Filter by POS',
    freqPosDistribution: 'POS Distribution',
    freqWordCloud: 'Word Cloud',
    freqClickToSearch: 'Click to search context',
    freqToggleStopWords: 'Filter stop words',
    freqNouns: 'Nouns',
    freqVerbs: 'Verbs',
    freqAdjectives: 'Adjectives',
    freqOthers: 'Others',
  },
  th: {
    title: 'Yanzhi Cube',
    subtitle: 'การจัดการคลังข้อมูล',
    findCorpora: 'ค้นหาคลังข้อมูลของคุณ',
    selectSource: 'เลือกภาษาต้นทาง',
    selectTarget: 'เลือกภาษาเป้าหมาย',
    pickSourceFirst: 'เลือกต้นทางก่อน',
    contribute: 'สนับสนุน',
    publications: 'สิ่งพิมพ์',
    corpora: 'คลังข้อมูล',
    synthetic: 'สังเคราะห์',
    dashboard: 'แดชบอร์ด',
    overviewTitle: 'ภาพรวมของคลังข้อมูล',
    totalPairs: 'คู่ประโยคทั้งหมด',
    languagesAvailable: 'ภาษาที่มีอยู่',
    tableNote: 'ตารางนี้แสดงคลังข้อมูล 10+ แห่ง ซึ่งคิดเป็น 62.50% ของคอลเลกชันทั้งหมด',
    contributors: 'ผู้สนับสนุนของเรา',
    corpus: 'คลังข้อมูล',
    sentences: 'ประโยค',
    percent: 'เปอร์เซ็นต์',
    opusCollection: 'คอลเลกชัน Yanzhi Cube',
    searchPlaceholder: 'ค้นหา...',
    sourceOpenSubtitles: 'OpenSubtitles',
    sourceUN: 'สหประชาชาติ',
    langChinese: 'จีน',
    langEnglish: 'อังกฤษ',
    langThai: 'ไทย',
    langVietnamese: 'เวียดนาม',
    langMalay: 'มาเลย์',
    // Search Results
    resourcesFound: 'พบทรัพยากร',
    headerCorpus: 'คลังข้อมูล',
    headerSentences: 'ประโยค',
    headerTokens: 'โทเค็น',
    headerSample: 'ตัวอย่าง',
    headerBilingual: 'สองภาษา',
    headerMonolingual: 'ภาษาเดียว',
    formatMoses: 'moses',
    formatTmx: 'tmx',
    formatTxt: 'txt',
    // Domains
    selectDomain: 'เลือกโดเมน',
    domainAll: 'โดเมนทั้งหมด',
    domainEcommerce: 'อีคอมเมิร์ซ',
    domainTourism: 'การท่องเที่ยว',
    domainBusiness: 'ธุรกิจ',
    domainEconomy: 'เศรษฐกิจระดับต่ำ',
    domainGeneral: 'ทั่วไป',
    // Dashboard Specific (Simple placeholder for TH)
    dashTitle: 'แดชบอร์ดสินทรัพย์ข้อมูล',
    dashSubtitle: 'ระบบจัดการคลังข้อมูล Yanzhi Cube',
    dashLastUpdated: 'อัปเดตล่าสุด',
    dashExport: 'ส่งออกรายงาน',
    dashViewOverview: 'ภาพรวม',
    dashViewBusiness: 'ข้อมูลเชิงลึกทางธุรกิจ',
    dashViewLanguage: 'คุณลักษณะทางภาษา',
    dashViewQuality: 'การควบคุมคุณภาพ',
    filterSource: 'แหล่งข้อมูล',
    filterSourceAll: 'ทั้งหมด',
    filterSourceOfficial: 'ทางการ',
    filterSourceCommunity: 'ชุมชน',
    filterSourceSynthetic: 'สังเคราะห์',
    filterDomain: 'โดเมน',
    filterMetric: 'ตัวชี้วัด',
    filterMetricQuality: 'คะแนนคุณภาพ',
    filterMetricVolume: 'ปริมาณ',
    filterMetricAlign: 'การจัดตำแหน่ง',
    filterMetricRojak: 'ความหนาแน่น Rojak',
    filterScenario: 'สถานการณ์',
    filterCategory: 'การจำแนกประเภท',
    labelSourceLang: 'ภาษาต้นทาง',
    labelTargetLang: 'ภาษาเป้าหมาย',
    labelKeyword: 'ค้นหาคำหลัก',
    btnSwap: 'สลับ',
    kpiRefinedPairs: 'คู่ประโยคที่ขัดเกลา',
    kpiAvgDim: 'มิติการบันทึกเฉลี่ย',
    kpiRojak: 'ความครอบคลุมภาษา Rojak',
    chartSentiment: 'การกระจายความรู้สึก',
    chartTimeline: 'ไทม์ไลน์การสะสม',
    chartTimelineSub: 'ติดตามการนำเข้าประจำวัน vs ปริมาณทั้งหมด',
    chartIntentTop: 'เจตนาสูงสุด',
    chartHeatmap: 'แผนที่ความร้อนเจตนา',
    chartPlatformSent: 'คะแนนความรู้สึกช่องทาง',
    labelPositive: 'บวก',
    labelNeutral: 'กลาง',
    labelNegative: 'ลบ',
    labelAngry: 'โกรธ',
    tabPresales: 'การปรึกษาหารือ',
    tabInsales: 'ธุรกรรม',
    tabAftersales: 'บริการ',
    tabLogistics: 'การดำเนินงาน',
    tabReviews: 'ข้อเสนอแนะ',
    txtAnomalyAlert: 'แจ้งเตือนความผิดปกติ',
    txtAnomalyDesc: 'พบความรู้สึก "โกรธ" พุ่งสูงขึ้นในชุดข้อมูล Channel C / การดำเนินงาน',
    txtInvestigate: 'ตรวจสอบชุดข้อมูล',
    txtNormalization: 'พจนานุกรมมาตรฐาน',
    txtLoanwords: 'คำยืมความถี่สูง',
    txtStyleDist: 'การกระจายสไตล์',
    // Sample Preview
    samplePreview: 'ตัวอย่าง',
    lblSourceText: 'ข้อความต้นทาง',
    lblRawInput: 'ข้อมูลดิบ (ภาษาพูด)',
    lblNormalized: 'มาตรฐาน (สะอาด)',
    lblLinguistic: 'ข้อมูลเชิงลึกทางภาษา',
    lblNormMap: 'แผนที่มาตรฐาน',
    lblLoanwords: 'คำยืมภาษาอังกฤษ',
    lblStyle: 'สไตล์',
    lblRojak: 'Rojak',
    lblPragmatic: 'ชั้นการปฏิบัติ',
    lblUserIntent: 'เจตนาผู้ใช้',
    lblSentiment: 'ความรู้สึก',
    lblVisual: 'ภาพ',
    lblJsonl: 'JSONL',
    lblNoneDetected: 'ตรวจไม่พบ',
    lblNoNormNeeded: 'ไม่จำเป็นต้องทำให้เป็นมาตรฐาน',
    lblDisplaying: 'แสดง {current} จาก {total} คู่',
    lblDetected: 'ตรวจพบ',
    lblNone: 'ไม่มี',
    // Tab Navigation
    tabDetail: 'รายละเอียดตัวอย่าง',
    tabKwic: 'การวิเคราะห์บริบท',
    tabStatistics: 'สถิติคำศัพท์',
    // Pagination
    paginationPrevious: 'ก่อนหน้า',
    paginationNext: 'หน้าถัดไป',
    // KWIC Analysis
    kwicTitle: 'การวิเคราะห์คำศัพท์ในบริบท',
    kwicKeywordPlaceholder: 'ป้อนคำศัพท์...',
    kwicContextWindow: 'หน้าต่างบริบท',
    kwicContext3: '±3 คำ',
    kwicContext5: '±5 คำ',
    kwicContext7: '±7 คำ',
    kwicSearch: 'ค้นหา',
    kwicExport: 'ส่งออก CSV',
    kwicLeftContext: 'บริบทซ้าย',
    kwicKeyword: 'คำศัพท์',
    kwicRightContext: 'บริบทขวา',
    kwicNoResults: 'ไม่พบผลลัพธ์',
    kwicResultCount: 'พบ {count} ผลลัพธ์',
    // Word Frequency Statistics
    freqTitle: 'ความถี่สูงของคำศัพท์',
    freqSubtitle: 'การวิเคราะห์ความถี่ใช้คำศัพท์ในคลังข้อมูล',
    freqTotalWords: 'คำศัพท์ทั้งหมด',
    freqUniqueWords: 'คำศัพท์ไม่ซ้ำกัน',
    freqMostCommon: 'คำที่พบบ่อยู่ย',
    freqFilterAll: 'ทั้งหมด',
    freqFilterNoun: 'นาม',
    freqFilterVerb: 'กริยา',
    freqFilterAdj: 'คำคุณธ์',
    freqSortByFreq: 'ตามความถี่',
    freqSortByAlpha: 'ตามตัวอักษร',
    freqWordColumn: 'คำศัพท์',
    freqCountColumn: 'จำนวน',
    freqPercentColumn: 'ร้อยละ',
    freqTrendColumn: 'แนวโน้',
    freqLoading: 'กำลังวิเคราะห์ความถี่...',
    freqNoData: 'ไม่มีข้อมูลความถี่',
  },
  vi: {
    title: 'Yanzhi Cube',
    subtitle: 'Quản lý ngữ liệu',
    findCorpora: 'Tìm ngữ liệu của bạn',
    selectSource: 'Chọn ngôn ngữ nguồn',
    selectTarget: 'Chọn ngôn ngữ đích',
    pickSourceFirst: 'Chọn nguồn trước',
    contribute: 'Đóng góp',
    publications: 'Ấn phẩm',
    corpora: 'Ngữ liệu',
    synthetic: 'Tổng hợp',
    dashboard: 'Bảng điều khiển',
    overviewTitle: 'Tổng quan bộ sưu tập',
    totalPairs: 'Tổng số cặp câu',
    languagesAvailable: 'Ngôn ngữ có sẵn',
    tableNote: 'Bảng này hiển thị 10+ ngữ liệu, chiếm tổng cộng 62,50% toàn bộ bộ sưu tập.',
    contributors: 'Người đóng góp',
    corpus: 'Ngữ liệu',
    sentences: 'Câu',
    percent: 'Tỷ lệ',
    opusCollection: 'Bộ sưu tập Yanzhi Cube',
    searchPlaceholder: 'Tìm kiếm...',
    sourceOpenSubtitles: 'OpenSubtitles',
    sourceUN: 'Liên hợp quốc',
    langChinese: 'Tiếng Trung',
    langEnglish: 'Tiếng Anh',
    langThai: 'Tiếng Thái',
    langVietnamese: 'Tiếng Việt',
    langMalay: 'Tiếng Mã Lai',
    resourcesFound: 'Tài nguyên được tìm thấy',
    headerCorpus: 'NGỮ LIỆU',
    headerSentences: 'CÂU',
    headerTokens: 'TOKENS',
    headerSample: 'MẪU',
    headerBilingual: 'SONG NGỮ',
    headerMonolingual: 'ĐƠN NGỮ',
    formatMoses: 'moses',
    formatTmx: 'tmx',
    formatTxt: 'txt',
    selectDomain: 'Chọn lĩnh vực',
    domainAll: 'Tất cả lĩnh vực',
    domainEcommerce: 'Thương mại điện tử',
    domainTourism: 'Du lịch & Văn hóa',
    domainBusiness: 'Kinh doanh & Thương mại',
    domainEconomy: 'Kinh tế tầm thấp',
    domainGeneral: 'Chung',
    dashTitle: 'Bảng điều khiển tài sản dữ liệu',
    dashSubtitle: 'Hệ thống quản lý ngữ liệu Yanzhi Cube',
    dashLastUpdated: 'Cập nhật lần cuối',
    dashExport: 'Xuất báo cáo',
    dashViewOverview: 'Tổng quan',
    dashViewBusiness: 'Thông tin doanh nghiệp',
    dashViewLanguage: 'Đặc điểm ngôn ngữ',
    dashViewQuality: 'Kiểm soát chất lượng',
    filterSource: 'Nguồn ngữ liệu',
    filterSourceAll: 'Tất cả',
    filterSourceOfficial: 'Chính thức',
    filterSourceCommunity: 'Cộng đồng',
    filterSourceSynthetic: 'Tổng hợp',
    filterDomain: 'Lĩnh vực',
    filterMetric: 'Chỉ số',
    filterMetricQuality: 'Điểm chất lượng',
    filterMetricVolume: 'Khối lượng',
    filterMetricAlign: 'Căn chỉnh',
    filterMetricRojak: 'Mật độ Rojak',
    filterScenario: 'Kịch bản',
    filterCategory: 'Phân loại',
    labelSourceLang: 'Ngôn ngữ nguồn',
    labelTargetLang: 'Ngôn ngữ đích',
    labelKeyword: 'Tìm kiếm từ khóa',
    btnSwap: 'Hoán đổi',
    kpiRefinedPairs: 'Cặp câu đã tinh chỉnh',
    kpiAvgDim: 'Kích thước chú thích trung bình',
    kpiRojak: 'Độ phủ ngôn ngữ Rojak',
    chartSentiment: 'Phân bố cảm xúc',
    chartTimeline: 'Dòng thời gian tích lũy',
    chartTimelineSub: 'Theo dõi lượng nhập hàng ngày so với tổng thể',
    chartIntentTop: 'Ý định hàng đầu',
    chartHeatmap: 'Bản đồ nhiệt ý định',
    chartPlatformSent: 'Điểm cảm xúc kênh',
    labelPositive: 'Tích cực',
    labelNeutral: 'Trung tính',
    labelNegative: 'Tiêu cực',
    labelAngry: 'Giận dữ',
    tabPresales: 'Tư vấn',
    tabInsales: 'Giao dịch',
    tabAftersales: 'Hỗ trợ',
    tabLogistics: 'Vận hành',
    tabReviews: 'Phản hồi',
    txtAnomalyAlert: 'Cảnh báo phát hiện bất thường',
    txtAnomalyDesc: 'Phát hiện sự gia tăng đột biến cảm xúc "Giận dữ" trong tập dữ liệu Kênh C / Vận hành trong 4 giờ qua.',
    txtInvestigate: 'Điều tra lô',
    txtNormalization: 'Từ điển chuẩn hóa',
    txtLoanwords: 'Từ mượn tần suất cao (Rojak)',
    txtStyleDist: 'Phân bố phong cách',
    // Sample Preview
    samplePreview: 'Xem trước mẫu',
    lblSourceText: 'Văn bản nguồn',
    lblRawInput: 'Đầu vào thô (Thông tục)',
    lblNormalized: 'Chuẩn hóa (Sạch)',
    lblLinguistic: 'Thông tin ngôn ngữ',
    lblNormMap: 'Bản đồ chuẩn hóa',
    lblLoanwords: 'Từ mượn tiếng Anh',
    lblStyle: 'Phong cách',
    lblRojak: 'Rojak',
    lblPragmatic: 'Lớp ngữ dụng',
    lblUserIntent: 'Ý định người dùng',
    lblSentiment: 'Cảm xúc',
    lblVisual: 'Trực quan',
    lblJsonl: 'JSONL',
    lblNoneDetected: 'Không phát hiện',
    lblNoNormNeeded: 'Không cần chuẩn hóa.',
    lblDisplaying: 'Hiển thị {current} / {total} cặp',
    lblDetected: 'ĐÃ PHÁT HIỆN',
    lblNone: 'KHÔNG',
    // Tab Navigation
    tabDetail: 'Chi tiết mẫu',
    tabKwic: 'Phân tích ngữ cảnh',
    tabStatistics: 'Thống kê tần suất',
    // Pagination
    paginationPrevious: 'Trang trước',
    paginationNext: 'Trang sau',
    // KWIC Analysis
    kwicTitle: 'Phân tích từ ngữ cảnh',
    kwicKeywordPlaceholder: 'Nhập từ khóa...',
    kwicContextWindow: 'Cửa sổ ngữ cảnh',
    kwicContext3: '±3 từ',
    kwicContext5: '±5 từ',
    kwicContext7: '±7 từ',
    kwicSearch: 'Tìm kiếm',
    kwicExport: 'Xuất CSV',
    kwicLeftContext: 'Ngữ cảnh trái',
    kwicKeyword: 'Từ khóa',
    kwicRightContext: 'Ngữ cảnh phải',
    kwicNoResults: 'Không tìm thấy kết quả',
    kwicResultCount: 'Tìm thấy {count} kết quả',
    // Word Frequency Statistics
    freqTitle: 'Tần suất từ vựng',
    freqSubtitle: 'Phân tích tần suất sử dụng từ vựng',
    freqTotalWords: 'Tổng số từ',
    freqUniqueWords: 'Số từ duy nhất',
    freqMostCommon: 'Từ thường gặp',
    freqFilterAll: 'Tất cả',
    freqFilterNoun: 'Danh từ',
    freqFilterVerb: 'Động từ',
    freqFilterAdj: 'Tính từ',
    freqSortByFreq: 'Theo tần suất',
    freqSortByAlpha: 'A B C',
    freqWordColumn: 'Từ vựng',
    freqCountColumn: 'Số lượng',
    freqPercentColumn: 'Tỷ lệ',
    freqTrendColumn: 'Xu hướng',
    freqLoading: 'Đang phân tích tần suất...',
    freqNoData: 'Chưa có dữ liệu tần suất',
  },
  ms: {
    title: 'Yanzhi Cube',
    subtitle: 'Pengurusan Korpus',
    findCorpora: 'Cari korpus anda',
    selectSource: 'Pilih bahasa sumber',
    selectTarget: 'Pilih bahasa sasaran',
    pickSourceFirst: 'Pilih sumber dahulu',
    contribute: 'Sumbang',
    publications: 'Penerbitan',
    corpora: 'Korpus',
    synthetic: 'Sintetik',
    dashboard: 'Papan Pemuka',
    overviewTitle: 'Gambaran Keseluruhan Koleksi',
    totalPairs: 'Jumlah Pasangan Ayat',
    languagesAvailable: 'Bahasa Tersedia',
    tableNote: 'Jadual ini memaparkan 10+ korpus, yang membentuk 62.50% daripada keseluruhan koleksi.',
    contributors: 'Penyumbang Kami',
    corpus: 'Korpus',
    sentences: 'Ayat',
    percent: '% daripada Jumlah',
    opusCollection: 'Koleksi Yanzhi Cube',
    searchPlaceholder: 'Cari...',
    sourceOpenSubtitles: 'OpenSubtitles',
    sourceUN: 'Bangsa-Bangsa Bersatu',
    langChinese: 'Cina',
    langEnglish: 'Inggeris',
    langThai: 'Thai',
    langVietnamese: 'Vietnam',
    langMalay: 'Melayu',
    resourcesFound: 'Sumber ditemui',
    headerCorpus: 'KORPUS',
    headerSentences: 'AYAT',
    headerTokens: 'TOKEN',
    headerSample: 'CONTOH',
    headerBilingual: 'DWIBAHASA',
    headerMonolingual: 'EKA BAHASA',
    formatMoses: 'moses',
    formatTmx: 'tmx',
    formatTxt: 'txt',
    selectDomain: 'Pilih Domain',
    domainAll: 'Semua Domain',
    domainEcommerce: 'E-dagang',
    domainTourism: 'Pelancongan & Budaya',
    domainBusiness: 'Perniagaan & Perdagangan',
    domainEconomy: 'Ekonomi Altitud Rendah',
    domainGeneral: 'Umum',
    dashTitle: 'Papan Pemuka Aset Data',
    dashSubtitle: 'Sistem Pengurusan Korpus Yanzhi Cube',
    dashLastUpdated: 'Terakhir Dikemaskini',
    dashExport: 'Eksport Laporan',
    dashViewOverview: 'Gambaran Keseluruhan',
    dashViewBusiness: 'Wawasan Perniagaan',
    dashViewLanguage: 'Ciri-ciri Bahasa',
    dashViewQuality: 'Kawalan Kualiti',
    filterSource: 'Sumber Korpus',
    filterSourceAll: 'Semua',
    filterSourceOfficial: 'Rasmi',
    filterSourceCommunity: 'Komuniti',
    filterSourceSynthetic: 'Sintetik',
    filterDomain: 'Domain',
    filterMetric: 'Metrik',
    filterMetricQuality: 'Skor Kualiti',
    filterMetricVolume: 'Jumlah',
    filterMetricAlign: 'Penjajaran',
    filterMetricRojak: 'Ketumpatan Rojak',
    filterScenario: 'Senario',
    filterCategory: 'Klasifikasi',
    labelSourceLang: 'Bahasa Sumber',
    labelTargetLang: 'Bahasa Sasaran',
    labelKeyword: 'Carian Kata Kunci',
    btnSwap: 'Tukar',
    kpiRefinedPairs: 'Pasangan Ayat Diperhalusi',
    kpiAvgDim: 'Dimensi Anotasi Purata',
    kpiRojak: 'Liputan Bahasa Rojak',
    chartSentiment: 'Taburan Sentimen',
    chartTimeline: 'Garis Masa Pengumpulan',
    chartTimelineSub: 'Menjejak pengambilan harian vs jumlah keseluruhan.',
    chartIntentTop: 'Niat Teratas',
    chartHeatmap: 'Peta Haba Niat',
    chartPlatformSent: 'Skor Sentimen Saluran',
    labelPositive: 'Positif',
    labelNeutral: 'Neutral',
    labelNegative: 'Negatif',
    labelAngry: 'Marah',
    tabPresales: 'Perundingan',
    tabInsales: 'Transaksi',
    tabAftersales: 'Sokongan',
    tabLogistics: 'Operasi',
    tabReviews: 'Maklum Balas',
    txtAnomalyAlert: 'Amaran Pengesanan Anomali',
    txtAnomalyDesc: 'Lonjakan tiba-tiba dalam sentimen "Marah" dikesan dalam set data Saluran C / Operasi dalam 4 jam terakhir.',
    txtInvestigate: 'Siasat Kelompok',
    txtNormalization: 'Kamus Penormalan',
    txtLoanwords: 'Kata Pinjaman Frekuensi Tinggi (Rojak)',
    txtStyleDist: 'Taburan Gaya',
    // Sample Preview
    samplePreview: 'Pratonton Contoh',
    lblSourceText: 'Teks Sumber',
    lblRawInput: 'Input Mentah (Bahasa Pasar)',
    lblNormalized: 'Dinormalkan (Bersih)',
    lblLinguistic: 'Wawasan Linguistik',
    lblNormMap: 'Peta Penormalan',
    lblLoanwords: 'Kata Pinjaman Inggeris',
    lblStyle: 'Gaya',
    lblRojak: 'Rojak',
    lblPragmatic: 'Lapisan Pragmatik',
    lblUserIntent: 'Niat Pengguna',
    lblSentiment: 'Sentimen',
    lblVisual: 'Visual',
    lblJsonl: 'JSONL',
    lblNoneDetected: 'Tiada dikesan',
    lblNoNormNeeded: 'Tiada penormalan diperlukan.',
    lblDisplaying: 'Memaparkan {current} dari {total} pasangan',
    lblDetected: 'DIKESAN',
    lblNone: 'TIADA',
    // Tab Navigation
    tabDetail: 'Butiran Contoh',
    tabKwic: 'Analisis Konteks Kata',
    tabStatistics: 'Statistik Frekuensi Kata',
    // Pagination
    paginationPrevious: 'Sebelumnya',
    paginationNext: 'Seterusnya',
    // KWIC Analysis
    kwicTitle: 'Kata Dalam Konteks',
    kwicKeywordPlaceholder: 'Masukkan kata kunci...',
    kwicContextWindow: 'Tingkap Konteks',
    kwicContext3: '±3 perkataan',
    kwicContext5: '±5 perkataan',
    kwicContext7: '±7 perkataan',
    kwicSearch: 'Cari',
    kwicExport: 'Eksport CSV',
    kwicLeftContext: 'Konteks Kiri',
    kwicKeyword: 'Kata Kunci',
    kwicRightContext: 'Konteks Kanan',
    kwicNoResults: 'Tiada hasil ditemui',
    kwicResultCount: 'Tjumpa {count} hasil',
    // Word Frequency Statistics
    freqTitle: 'Statistik Frekuensi Kata',
    freqSubtitle: 'Analisis penggunaan frekuensi kata dalam korpus',
    freqTotalWords: 'Jumlah Kata',
    freqUniqueWords: 'Kata Unik',
    freqMostCommon: 'Kata Kerap',
    freqFilterAll: 'Semua',
    freqFilterNoun: 'Kata Nama',
    freqFilterVerb: 'Kata Kerja',
    freqFilterAdj: 'Kata Sifat',
    freqSortByFreq: 'Mengikut Frekuensi',
    freqSortByAlpha: 'Mengikut A-B-C',
    freqWordColumn: 'Perkataan',
    freqCountColumn: 'Kiraan',
    freqPercentColumn: 'Peratusan',
    freqTrendColumn: 'Arah Aliran',
    freqLoading: 'Menganalisis frekuensi kata...',
    freqNoData: 'Tiada data frekuensi',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
